[project]
name = "data-process-interface"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "mkdocs>=1.6.1",
    "plotly>=5.24.1",
    "polars>=1.14.0",
    "pyqt6>=6.7.1",
]
